### ISSUE TITLE
[問題]404 WebSocket Upgrade Failure

### ISSUE THREAD

**Issue by VincentX0905** [Ruokwok/NukkitPanel#2]
**WHYYYYY?**
這是什麼問題?

![Screenshot 2021-10-26 230509](https://user-images.githubusercontent.com/76867533/138907274-903f6ff8-da08-4b64-8bb4-b3db3d560fb6.png)

**Comment by Ruokwok** [comment]
请问是在什么情况发生的这个错误

**Comment by VincentX0905** [comment]
安裝此插件時
我只調整配置文件而已

**Comment by Ruokwok** [comment]
更换版本安装试试，请先不要修改配置文件

**Comment by VincentX0905** [comment]
我試試看

**Comment by VincentX0905** [comment]
1.17版一樣顯示 404 WebSocket Upgrade Failure
是不是我少裝什麼東西?

**Comment by Ruokwok** [comment]
访问http://地址:端口/admin/login，有显示登录页面吗？

**Comment by VincentX0905** [comment]
沒有欸QQ
我使用的控制面板 McManager

**Comment by Ruokwok** [comment]
此插件使服务器可以通过HTTP访问网页控制，本身就是控制面板，如果已经使用MCSM就没必要使用此插件。
关于此插件的详细内容请见https://www.minebbs.com/resources/nukkit-panel.2054/

**Comment by VincentX0905** [comment]
OK好的!
